version: "3.8"

services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j-graphrag
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/senha123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,apoc.meta.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,apoc.meta.*"
    volumes:
      - ./data:/data
